# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alex Howington
tagline:          'Web Developer'
description:      "Web developer ........... (what's the opposite of extraordinaire?)"
url:              http://alexhowington.com
baseurl:          ''

author:
  name:           'Alex Howington'
  url:            https://twitter.com/alexhowington

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ash106/ash106.github.io

collections:
- projects

gems: [jekyll-gist, jekyll-paginate, jekyll-sitemap]
